apiVersion: v1
kind: ConfigMap
metadata:
  # Put version number in name of configmap, ideal for easier rollbacks
  name: frontend-config-v1
  # always define your target namespace.  This can be overridden via helm charts vars
  namespace: kbps
  labels:
    # added to all resources for ease of later examination and selector usage.
    app: journal
    tier: frontend
data:
  journalEntries: "10"
