apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  # always define your target namespace.  This can be overridden via helm charts vars
  namespace: kbps
  labels:
    # added to all resources for ease of later examination and selector usage.
    app: redis
    role: slave
    tier: backend
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      affinity:
        # FAULT_TOLERANCE: Avoid Pods being placed into a single node
        ## https://cloudmark.github.io/Node-Management-In-GKE/#pod-anti-affinity-rules
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: redis
                role: slave
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
