apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-apps
  labels:
    monitoring: apps
spec:
  selector:
    matchLabels:
      monitoring: apps
  endpoints:
    - port: http-metrics
