apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adminuser01-admin-CRB
subjects:
- kind: User
  name: adminuser01@ntnxlab.local # AD User Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # must match the name of a Role or ClusterRole to bind to
  apiGroup: rbac.authorization.k8s.io
