apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  # always define your target namespace.  This can be overridden via helm charts vars
  namespace: kbps
  labels:
    # added to all resources for ease of later examination and selector usage.
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
