name: GitHub Actions Workflow

# defaults:
#   run:
#     # Needed to load .bashrc for kubectl plugins
#     shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      # Put your branch name HERE, default is "feat-doc-updat"
      - main
    paths-ignore:
      - 'docs/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

############### Start var config #########
env:
  # PROJECT_NAME should be the same as project_name in cookiecutter.json
  ENVIRONMENT: "kalm-main-8-2"

jobs:
  login:
    runs-on: self-hosted
    environment: HPOC_CICD
    container:
      image: ntnxdemo/calm-dsl-utils:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      volumes:
        - ${{ github.workspace }}:/dsl-workspace
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Staging Environment Secrets
        run: |
          pwd
          ls
          mkdir -p .local/_common
          echo "${{ secrets.NTNX_SSH_PRIVATE_KEY }}" > ${{ github.workspace }}/.local/_common/nutanix_key
          echo "${{ secrets.NTNX_SSH_PUB_KEY }}" > ${{ github.workspace }}/.local/_common/nutanix_public_key
          cp ./secrets.yaml.example ./secrets.yaml
          sed -i "s/docker_hub_user: required_secret/docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}/g" ./secrets.yaml
          sed -i "s/docker_hub_password: required_secret/docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}/g" ./secrets.yaml
          sed -i "s/required_secret/${{ secrets.HPOC_REQUIRED_SECRET }}/g" ./secrets.yaml
          ./init_local_configs.sh .local/_common/nutanix_key .local/_common/nutanix_public_key ${ENVIRONMENT} true
      # - name: Install Pre-Reqs
      #   run: |
      #     sudo add-apt-repository ppa:rmescandon/yq
      #     sudo apt update
      #     sudo apt install yq -y
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: self-hosted
  #   environment: HPOC_CICD
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: Prin
  #       run: |
  #         make print-vars ENVIRONMENT=kalm-main-8-2

