name: GitHub Actions Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: HPOC_CICD
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Staging Environment Secrets
        run: |
          echo "${{ secrets.NTNX_SSH_PRIVATE_KEY }}" > ${{ github.workspace }}/.local/_common/nutanix_key
          echo "${{ secrets.NTNX_SSH_PUB_KEY }}" > ${{ github.workspace }}/.local/_common/nutanix_public_key
          cp ./secrets.yaml.example ./secrets.yaml
          sed -i "s/docker_hub_user: required_secret/docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}/g" ./secrets.yaml
          sed -i "s/docker_hub_password: required_secret/docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}/g" ./secrets.yaml
          sed -i "s/required_secret/${{ secrets.HPOC_REQUIRED_SECRET }}/g" ./secrets.yaml
          ./init_local_configs.sh .local/_common/nutanix_key .local/_common/nutanix_public_key kalm-main-8-2 true
          make docker-login
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ntnxdemo/calm-dsl-utils:latest
            options: -v ${{ github.workspace }}:/dsl-workspace
            run: |
              make print-vars ENVIRONMENT=kalm-main-8-2
      - name: Install Pre-Reqs
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Staging Environment Secrets
        run: |
          make print-vars ENVIRONMENT=kalm-main-8-2
      - run: echo "🍏 This job's status is ${{ job.status }}."

