name: cloud-native-calm-builds-workflow

defaults:
  run:
    # Needed to load .bashrc for kubectl plugins
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      # Put your branch name HERE, default is "feat-doc-updat"
      - main
    paths-ignore:
      - 'docs/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ENVIRONMENT_NAME: kalm-main-8-2

jobs:
  prepare:
    runs-on: self-hosted
    environment: kalm-main-cicd
    container:
      image: ntnxdemo/calm-dsl-utils:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      options: -t
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Staging Environment Secrets
        run: |
          env
          git config --global --add safe.directory $GITHUB_WORKSPACE
          mkdir -p .local/_common
          echo "${{ secrets.NTNX_SSH_PRIVATE_KEY }}" > .local/_common/nutanix_key
          echo "${{ secrets.NTNX_SSH_PUB_KEY }}" > .local/_common/nutanix_public_key
          cp ./secrets.yaml.example ./secrets.yaml

          MOD_DOCKER_HUB_PASS=$(echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | sed 's/\W/\\&/g')
          sed -i "s/docker_hub_user: .*/docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}/g" ./secrets.yaml
          sed -i "s/docker_hub_password: .*/docker_hub_password: $MOD_DOCKER_HUB_PASS/g" ./secrets.yaml

          MOD_GH_SECRET=$(echo "${{ secrets.GH_SECRET }}" | sed 's/\W/\\&/g')
          sed -i "s/github_user: .*/github_user: ${{ secrets.GH_USER }}/g" ./secrets.yaml
          sed -i "s/github_password: .*/github_password: $MOD_GH_SECRET/g" ./secrets.yaml

          MOD_COMMON_SECRET=$(echo "${{ secrets.COMMON_SECRET }}" | sed 's/\W/\\&/g')
          sed -i "s/required_secret/$MOD_COMMON_SECRET/g" ./secrets.yaml
      - name: Initialize Environment Configs
        run: |
          ./init_local_configs.sh .local/_common/nutanix_key .local/_common/nutanix_public_key $ENVIRONMENT_NAME true
          make print-vars ENVIRONMENT=$ENVIRONMENT_NAME
      - name: Initialize DSL Config
        run:  |
          make check-dsl-init ENVIRONMENT=$ENVIRONMENT_NAME
      - name: Provision Linux Bastion Host Endpoint
        run: make init-bastion-host-svm ENVIRONMENT=$ENVIRONMENT_NAME
      # - name: Initialize All Helm Charts
      #   run:  make create-all-helm-charts publish-all-new-helm-bps ENVIRONMENT=$ENVIRONMENT_NAME
      # - name: Provision Calm Endpoint & Runbook Infra
      #   run: make init-runbook-infra ENVIRONMENT=$ENVIRONMENT_NAME
      # - name: Provision NKE Karbon Production Cluster
      #   run: make init-kalm-cluster ENVIRONMENT=$ENVIRONMENT_NAME
      # - name: Launch All Helm Charts
      #   run: make launch-all-helm-charts ENVIRONMENT=$ENVIRONMENT_NAME
      # - name: Cleanup & Reset Cluster
      #   run: make bootstrap-reset-all ENVIRONMENT=$ENVIRONMENT_NAME

