name: GitHub Actions Workflow

# defaults:
#   run:
#     # Needed to load .bashrc for kubectl plugins
#     shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      # Put your branch name HERE, default is "feat-doc-updat"
      - main
    paths-ignore:
      - 'docs/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prepare:
    runs-on: self-hosted
    environment: "kalm-main-8-2"
    container:
      image: ntnxdemo/calm-dsl-utils:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Staging Environment Secrets
        run: |
          mkdir -p .local/_common
          echo "${{ secrets.NTNX_SSH_PRIVATE_KEY }}" > .local/_common/nutanix_key
          echo "${{ secrets.NTNX_SSH_PUB_KEY }}" > .local/_common/nutanix_public_key
          cp ./secrets.yaml.example ./secrets.yaml
          sed -i "s/docker_hub_user: required_secret/docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}/g" ./secrets.yaml
          MOD_DOCKER_HUB_PASS=$(echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | sed 's/\W/\\&/g')
          sed -i "s/docker_hub_password: .*/docker_hub_password: $MOD_DOCKER_HUB_PASS/g" ./secrets.yaml
          sed -i "s/required_secret/${{ secrets.HPOC_REQUIRED_SECRET }}/g" ./secrets.yaml
      - name: Initialize Environment Configs
        run: |
          ./init_local_configs.sh .local/_common/nutanix_key .local/_common/nutanix_public_key ${KALM_ENVIRONMENT} true
          make print-vars ENVIRONMENT=${KALM_ENVIRONMENT}


