name: Calm DSL Pipeline
on:
  push:
    #branches-ignore:
      #- '**'
    branches:
      # Put your branch name HERE, default is "feat-doc-updat"
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ENVIRONMENT: "kalm-main-20-3"

jobs:
  # Checkout Git repo and copy .local with secrets folder to github workspace
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ntnxdemo/calm-dsl-utils:latest
            options: -v ${{ github.workspace }}:/dsl-workspace
            run: |
              ls ${{ github.workspace }}
              pwd
              make help
