name: GitHub Actions Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Pre-Reqs
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: List files in the repository
        run: |
          ls -alth ${{ github.workspace }}
          pwd
          cp ./secrets.yaml.example ./secrets.yaml
          sed -i "s/required_secret/nx2Tech404!/g" ./secrets.yaml
          ./init_local_configs.sh .local/_common/nutanix_key .local/_common/nutanix_public_key kalm-main-8-2 true
          make help
          make docker-login
          make print-vars ENVIRONMENT=kalm-main-8-2
      - run: echo "🍏 This job's status is ${{ job.status }}."

